version: "3.7"

services:
  gitea:
    image: gitea/gitea:1.11.1
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN="${IP_VM}"
      - SSH_LISTEN_PORT=22
      - SSH_PORT=2222
      - ROOT_URL="http://${IP_VM}:3000/"
      - DOMAIN="${IP_VM}"
      - INSTALL_LOCK=true
    volumes:
      - /data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"

  etcd:
    image: quay.io/coreos/etcd:v3.4.4
    container_name: etcd
    restart: unless-stopped
    environment:
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LOGGER=zap
    volumes:
      - /data/etcd:/etcd-data

  agola:
    image: sorintlab/agola:v0.5.0
    command: "serve --components all-base,executor --config /data/agola/config.yml"
    container_name: agola
    restart: unless-stopped
    volumes:
      - /data/agola:/data/agola
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"