version: "3.7"

services:
  gitea:
    image: gitea/gitea:1.19
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN="${IP_VM}"
      - SSH_LISTEN_PORT=22
      - SSH_PORT=2222
      - ROOT_URL="http://${IP_VM}:3000/"
      - DOMAIN="${IP_VM}"
      - INSTALL_LOCK=true
      - GITEA__webhook__ALLOWED_HOST_LIST="*"
    volumes:
      - /data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"

  agola:
    image: sorintlab/agola:v0.8.0
    command: "serve --components all-base,executor --config /data/agola/config.yml"
    container_name: agola
    restart: unless-stopped
    volumes:
      - /data/agola:/data/agola
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"